version: "3.9"
services:
  web:
    build: .
    image: spy_agency
    ports:
      - "9091:8000"
    command: python /code/manage.py runserver 0:8000
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: postgres:13
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  migration:
    image: spy_agency
    command: python manage.py migrate spy_agency && python manage.py migrate && python manage.py loaddata spy_agency --noinput
    volumes:
      - .:/code
    depends_on:
      - db

volumes:
  postgres_data:
